//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_New_Paradise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Employee_ID { get; set; }
        public string Employee_Name { get; set; }
        public string Employee_Phone { get; set; }
        public string Employee_Email { get; set; }
        public double Employee_Salary { get; set; }
        public int Employee_Experience { get; set; }
    }
}
