//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_New_Paradise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicesTable
    {
        public int Service_ID { get; set; }
        public string Service_Namee { get; set; }
        public double Service_Price { get; set; }
        public int Service_Time { get; set; }
        public string Service_Description { get; set; }
        public string Service_Image { get; set; }
    }
}
